### ISSUE TITLE
Add Gold sponsor, Eyeframe

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2024#17]
Add a sponsor, like the other sponsors are shown. (Gold Sponsor)
![Copy of Untitled (3)](https://github.com/user-attachments/assets/9efe0d27-7d0e-4de5-b9d2-e77b375cb4d4)

**Comment by Git-Harshit** [comment]
Thanks for attaching two image variants.
I can add this sponsor card similar to how other sponsors are added under index.html.
Please assign this issue to me and I will be happy to raise a PR on it.

**Comment by Git-Harshit** [comment]
Is there any associated website for this sponsor?
Simple Internet search on Bing did not get me any related results. If no link exists, I may use a broken '#' URL instead.

**Comment by Git-Harshit** [comment]
In order to make any contribution under this or any other issue in the repository, just using **_Hacktoberfest_** label here does not count.

Here's what does:
![image](https://github.com/user-attachments/assets/bcc8a489-5cf2-414d-94be-9a1d503cc1e5)

Please consider adding hacktoberfest label to the repository description or use hacktoberfest-accepted label on every accepted PR instead to make that count for [Hacktoberfest](https://hacktoberfest.com/) submissions.
